### ISSUE TITLE
ENV variable load and merge two config files

### ISSUE THREAD

**Issue by vicentecastroa** [lorenwest/node-config#643] opened 2021-03-05 19:54 UTC
### I'm submitting a ... 
  - [ X ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
I have multiple config files for different versions and environments. When running a specific environment, it's merging config files that contain  `ENV` in their name.
#### Steps to reproduce
1. Have these files in `/config`:
```
config
|-staging.json
|-stagingV3.json
```
2. Run:
```
SET NODE_ENV=stagingV3 && SET APP_VERSION=3 && nodemon src/
```
3. This happen when console.log `config.authentication`
![image](https://user-images.githubusercontent.com/13738469/110166459-62399380-7dc2-11eb-85ce-b81b4d30c0a7.png)

### What is the expected behavior?
To load only `stagingV3.json`

### Please tell us about your environment:

 -  node-version: 10.0.0

**Comment by markstos** [comment] 2021-04-09 14:55
> SET NODE_ENV=stagingV3 && SET APP_VERSION=3 && nodemon src/

What shell language is this?

You should inspect `process.env.NODE_ENV` within the app to confirm you are actually setting `NODE_ENV` as intended.

**Comment by markstos** [comment] 2021-05-05 20:40
Closing due to lack of follow-up information.

**Closed by markstos** 2021-05-05 20:40 UTC
Labels: pending-more-information
