### ISSUE TITLE
Get returns utilWarnings

### ISSUE THREAD

**Issue by dariospadoni** [lorenwest/node-config#232] opened 2015-07-06 14:11 UTC
Hello 
I've a weird issue. 
I have the following config file 
```
module.exports = {
  server:{
    port:3000
    router: {
      stripTrailingSlash:true
    }
    routes:{
      cors: {
        additionalHeaders: ['language','Language']
      }
    }
  }
}
```
and I access this config in this way:

```
server = new Hapi.Server()
server.connection(config.get('server'))
```
However I got an error when I run the server:
```
[1] "util" is not allowed
[2] "get" is not allowed
[3] "has" is not allowed
[4] "watch" is not allowed
[5] "setModuleDefaults" is not allowed
[6] "makeHidden" is not allowed
[7] "makeImmutable" is not allowed
[8] "getConfigSources" is not allowed
[9] "_loadFileConfigs" is not allowed
[10] "_parseFile" is not allowed
[11] "_attachProtoDeep" is not allowed
[12] "_cloneDeep" is not allowed
[13] "_equalsDeep" is not allowed
[14] "_diffDeep" is not allowed
[15] "_extendDeep" is not allowed
[16] "_stripYamlComments" is not allowed
[17] "_stripComments" is not allowed
[18] "_isObject" is not allowed
[19] "_initParam" is not allowed
[20] "_getCmdLineArg" is not allowed←[0m
```

If in the config I set 
```
 cors: true
```
it works.

If I don't use the config module and I pass the same configuration to server.connection() it works.

It seems that config.get() returns also some extra properties and not only the specified configuration...any idea? 

I'm using the latest version with win7.

**Comment by markstos** [comment] 2015-07-06 14:53
Closing as duplicate of #223. Review that Issue for explanation and tentative plans for a fix.

**Closed by markstos** 2015-07-06 14:53 UTC
