### ISSUE TITLE
Setting a value of existing config parameter

### ISSUE THREAD

**Issue by ne0c0de** [lorenwest/node-config#452] opened 2017-11-27 12:00 UTC
Hi,

I'm using this config library to store the initial configuration of my app. But i want to be able to set a value of the current config value dynamically and after this operation i want that config value should be placed on config.json as well.

So after restart of my app, it will continue to use the new setting.

I searched about previous issue but couldn't find usefull information for me.

Is is possible?

**Comment by markstos** [comment] 2017-11-27 14:10
No. node-config is immutable by design. More context is available if you search the project for "immutable".

Dupe of #418.

**Closed by markstos** 2017-11-27 14:10 UTC
