### ISSUE TITLE
diffDeep get not correct result

### ISSUE THREAD

**Issue by zyf0330** [lorenwest/node-config#457] opened 2018-01-02 08:52 UTC
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
```

	config.util.diffDeep(
		{a: {b: 1, c: 2}}, {a: {b: 1}}
	)
	config.util.diffDeep(
		{a: {b: 1, c: 2}}, {a: {}}
	)
```
got 
```
{ a: {} }
{ a: {} }
```

### What is the expected behavior?
```
{}
{ a: {} }
```
### Please tell us about your environment:

 -  node-config version: newest
 -  node-version:  8.9.0
 
### Other information
I think, `diff` should return `null` if there is no diff like `diff({}, {}) == null` and `diff({}, null) == {}`
(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment] 2018-01-02 12:34
In practice, how does the current behavior cause is to return a bad config?

**Comment by zyf0330** [comment] 2018-01-03 01:38
Like this example 
```
config.util.diffDeep(
		{a: {b: 1, c: 2}}, {a: {b: 1}}
	)
```
, when I remove a prop of one child obj. Now `diffDeep` compares last to first, so it should give result `{}`.

**Comment by markstos** [comment] 2018-01-03 15:29
Thanks, but what you are trying to do *in your config files* that isn't working expected?  I'm looking for examples of your config files that aren't merging as expected.

There are other tools to deeply compare objects, our `diffDeep` is particularly designed to merge config files.

**Comment by lorenwest** [comment] 2018-01-03 15:45
The `diffDeep` tool doesn't run in the main code path of `node-config`. It's a convenience method for describing the differences between default configuration values and the values running in a specific deployment.

It works in a specific way for this purpose, and produces consistent results. If these results aren't to your liking, I can't classify it as a bug.

If you would like to discuss changing the current behavior, StackOverflow is the best place to have that discussion.  Closing this as not a bug.

**Closed by lorenwest** 2018-01-03 15:45 UTC
