### ISSUE TITLE
Overriding fields when using environment variables

### ISSUE THREAD

**Issue by rightisleft** [lorenwest/node-config#363] opened 2016-11-29 20:02 UTC
I'm trying to implement a custom-environment-variables.json file to get my ENV vars to work correctly with heroku. 

```
➜  config git:(master) ✗ tree
.
├── custom-environment-variables.json
├── default.json
└── test.json

0 directories, 3 files
➜  config git:(master) ✗
```

I have entries for SERVER_DATABASE_NAME, and SERVER_TEST_DATABASE_NAME in my .zshrc file. This allows Dependency Injection to toggle between contexts. 

If both default.json and test.json need to have their own unique values for a config.database.name, how do i fork that when custom-environment-variables is the final authority?

**Comment by markstos** [comment] 2016-12-05 19:24
Set different environment variables when you are testing. 

For example, if you are running tests via `gulp test`, in your gulpfile you can set environment variables with `process.env.SERVER_DATABASE_FOO`.

I'm closing this because it's not a bug report.

**Closed by markstos** 2016-12-05 19:24 UTC
