### ISSUE TITLE
Take parser out in a separate project

### ISSUE THREAD

**Issue by tamtakoe** [lorenwest/node-config#245] opened 2015-09-04 13:42 UTC
Take `parseString` out in a separate git/npm project, please

**Comment by markstos** [comment] 2015-09-04 14:14
Closing as a dupe of #181 Note that `node-rechoir` has this basic functionality already.

**Closed by markstos** 2015-09-04 14:14 UTC

**Comment by markstos** [comment] 2015-09-04 14:17
@tamtakoe If you prefer exactly how node-config does this over node-rechoir, you are welcome to put the open source license to use and copy the code into a module of your own that you document and publish. Let us know if you get that far, then we'll have an alternative to `node-rechoir` to consider.

**Comment by markstos** [comment] 2015-09-04 14:37
Regarding `node-rechoir`, see the linked #181 ticket for context. Looks like we also considered the `interpret` module. 

Regarding the warning, see https://github.com/lorenwest/node-config/wiki/Environment-Variables#suppress_no_config_warning

Also, searching for the warning in the source code would have quickly found the environment variable used to surpress it. 

Further conversation about splitting out the config file loading / parsing can happen in #181 if you are interested.

**Comment by tamtakoe** [comment] 2015-09-04 14:54
I hide warnings, thank! I think I put +1 in #181 :-)
