### ISSUE TITLE
not possible to run project with ts-node and ts config files

### ISSUE THREAD

**Issue by PavelPolyakov** [lorenwest/node-config#437] opened 2017-10-06 17:41 UTC
### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
I want to use `ts` config files AND  run my project using `ts-node`.
Current behaviour - everything fails. I believe that programmatically registered `ts-node` is conflicting with the one who is running the application.

Here is the reproduction.
Non working repo with `ts` config files:
https://github.com/PavelPolyakov/config-ts-vs-ts-node/tree/ts
![image](https://user-images.githubusercontent.com/839290/31290772-f9679fb6-aacd-11e7-87a5-d877e675c33a.png)

Working repo, where config files are `js` files:
https://github.com/PavelPolyakov/config-ts-vs-ts-node/tree/master
![image](https://user-images.githubusercontent.com/839290/31290807-170fe398-aace-11e7-921a-0a698b68980f.png)

### What is the expected behavior?
default `ts-node` application run should work

### Please tell us about your environment:

 -  node-config version: v6.11.3
 -  node-version: v6.11.3

**Comment by markstos** [comment] 2017-10-06 18:22
Have you reviewed the other issues that relate to TypeScript? https://github.com/lorenwest/node-config/search?q=TypeScript&type=Issues&utf8=%E2%9C%93

**Comment by PavelPolyakov** [comment] 2017-10-06 18:33
@markstos 
yes. I've participated this one, for example:
https://github.com/lorenwest/node-config/issues/416

Actually I think that there should be no seamless typescript format support in `node-config`, as usually you need to know (have control on) how your `typescript` file converts into javascript and executes after.

But as long as it is present - I think the bug is actual.

**Comment by electroma** [comment] 2018-01-07 13:30
Face the issue. The root cause is double registration of ts-node.
ts-node maintainer has [rejected to introduce re-registration fix into ts-node](https://github.com/TypeStrong/ts-node/issues/409). Actually he said he's going to throw an error in the future version.

I see several options:
1. Remove ts-node registration from node-config and expect app code to do it
2. Add configuration option to allow disable ts-node re-registration
3. Detect existing ts(x)-file handler and do not register ts-node in this case

I like option 3 the most.
Your thoughts?

**Comment by lorenwest** [comment] 2018-01-07 16:15
Can it be determined that `ts-node` has already been registered? Seems like an easy fix to skip registration if you can make this determination.

**Comment by lorenwest** [comment] 2018-01-07 16:21
Looks like you've answered that in #458  - approved and merged. Thanks for providing the fix.

**Comment by electroma** [comment] 2018-01-07 16:31
Thank you @lorenwest ! 
Please let me know how much time will it take to publish new version to the central NPM repo.

**Comment by lorenwest** [comment] 2018-01-07 16:35
No reason it can't go out today.

**Comment by lorenwest** [comment] 2018-01-07 19:04
Published today in config@1.29.1

**Comment by electroma** [comment] 2018-01-08 10:26
@lorenwest Please merge a little fix of that fix. Sorry about that.

**Comment by lorenwest** [comment] 2018-01-08 17:08
I was going to ask for a test, but it seemed like a small fix. This time to get this in I'd like you to add a test.

**Comment by electroma** [comment] 2018-01-08 20:09
@lorenwest done!
Thank you for keeping the quality bar high!

**Comment by lorenwest** [comment] 2018-01-09 17:17
Will try to get this in today

**Closed** 2018-01-13 01:01 UTC

**Comment by lorenwest** [comment] 2018-01-13 01:05
Published to npm @1.29.2
