### ISSUE TITLE
local-instance.json is loaded before local.json5

### ISSUE THREAD

**Issue by TheRoSS** [lorenwest/node-config#475] opened 2018-03-02 14:46 UTC
### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?
default.json5
```javascript
{
  "apps": [],
}
```

local.json5
```javascript
{
  "apps": [
    "aaaa",
    "bbbb",
    "cccc",
    "dddd"
  ]
}
```

local-instance.json
```javascript
{
  "apps": [ "zzzz" ],
}
```

run.js
```javascript
console.log("CONFIG:", require("config"));
```

Run script:
```
NODE_APP_INSTANCE=instance  node run.js
```

The final config is:
```javascript
{ apps: [ 'aaaa', 'bbbb', 'cccc', 'dddd' ] }
```

### What is the expected behavior?
The final config should be:
```javascript
{ apps: [ 'zzzz' ] }
```

### Please tell us about your environment:

 -  node-config version: 1.30.0
 -  node-version: any
 

### Other information

If you track the config loading order than you will receive following lines:
```
config/default.json5 { apps: [] }
config/local-instance.json { apps: [ 'zzzz' ] }
config/local.json5 { apps: [ 'aaaa', 'bbbb', 'cccc', 'dddd' ] }
```
As you can see from this the local-instance is loaded before local.json5

Next...
If you rename `local-instance.json` to `local-instance.json5` or `local.json5` to `local.json` than the order of loading and the final config will be correct

**Comment by iMoses** [comment] 2019-06-29 16:15
@markstos this is a duplicate of #512 which is solved by #561

**Closed** 2019-06-30 01:09 UTC
Labels: duplicate
