### ISSUE TITLE
local.json config bug

### ISSUE THREAD

**Issue by KievDevel** [lorenwest/node-config#421] opened 2017-05-25 15:20 UTC
Hi. I set up a couple of files in config directory: local.json, default.json, production.json, staging.json
When I tryed to get config from production.json and NODE_ENV was set as production I always got config from local.json 
Renaming local.json to development.json fixed the issue, but it isn't clear that we can't make local.json config file.

**Comment by markstos** [comment] 2017-05-25 15:37
Closing as dupe of #325. As the other ticket mentions, the behavior of "local.js" *is* documented and intentional. You can rename your "local" NODE_ENV to another value like "laptop" that doesn't conflict. 

More related discussion is in #337

**Closed by markstos** 2017-05-25 15:37 UTC
