### ISSUE TITLE
Support using config from node_modules

### ISSUE THREAD

**Issue by domharrington** [lorenwest/node-config#482] opened 2018-05-10 00:36 UTC
### I'm submitting a ... 
  - [x] feature request

### What is the current behavior?
I'm using this module inside of my npm module which will be published onto npm as a CLI program. The reason why I'm using it is to swap in config variables for things that will change from development to production e.g. API endpoint URLs.

When I `npm install` my module and execute it, `require('config')` inside my module attempts to load from `process.cwd()` which isn't where I expect it to look. 

This has been raised before:
https://github.com/lorenwest/node-config/issues/201#issuecomment-76051276
https://github.com/lorenwest/node-config/issues/138

I worry that changing people's environment variables then reverting them back to previous values is a little risky. Not to mention the caching issue with `require.cache`.

### What is the expected behavior?
What I would love is to be able to pass in the config dir at some point during construction.

```
const config = require('config')(path.join(__dirname, '/config'));
```

I'm fully aware that this is a massive change to the module. Maybe this doesn't belong here, maybe it belongs in some other `config-module` module, where you could do something like:

```
const config = require('config-module')('<module-name>', path.join(__dirname, '/config'));
```

And this could handle the `NODE_CONFIG_DIR` set/unset song and dance. Having it as a separate module would mean we don't pollute the global require cache, if the parent codebase wants to also use `config`. Providing the <module-name> would allow for an internal cache, if multiple npm modules want to use this independently.

Do you have any thoughts on the above? There may be reasons why this isn't possible; you definitely know more about how config works than I do. Thanks!

### Please tell us about your environment:

 -  node-config version: 1.30.0
 -  node-version: 9.5.0
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment] 2018-05-11 19:48
Closing as duplicate of #225.

**Comment by iMoses** [comment] 2019-07-17 14:56
@markstos you said you'll be closing this but you didn't :)

**Closed** 2019-07-17 15:09 UTC
Labels: duplicate
