### ISSUE TITLE
WARNING: No configurations found in configuration directory:/config

### ISSUE THREAD

**Issue by Bharwcb** [lorenwest/node-config#403] opened 2017-03-31 18:00 UTC
I am building an electron app, using `./config/config.json` as a storage for sensitive 3rd party API credentials.

config.json:
`{
  "credentials": {
  	"id": "123",
  	"secret": "456"
  }
}`

And when calling them in main.js:
`const config = require('config');`
`const id = config.get('credentials.id');`
`const secret = config.get('credentials.secret');`

This works locally when running `electron .` through terminal.  

However, when packaging the electron app (via '[electron-packager](https://github.com/electron-userland/electron-packager)'), Node Config cannot locate the configurations within my config directory.  I receive the errors: 

`WARNING: No configurations found in configuration directory:/config`
`Uncaught Error: Configuration property "credentials.id" is not defined`

Any expected conflict when using Node Config with Electron/ Electron Packager?

**Comment by markstos** [comment] 2017-03-31 18:39
Closing, as you provided no indication that you searched the issue tracker for "electron" before opening a new issue.  

Dupe of #368.

**Closed by markstos** 2017-03-31 18:39 UTC

**Comment by EyuTes** [comment] 2017-11-17 20:45
What is the cause for the following error
WARNING: No configurations found in configuration directory

WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

**Comment by markstos** [comment] 2017-11-17 21:02
@EyuTes Search the wiki and issue tracker.

**Comment by DamithaPerera** [comment] 2020-02-25 08:02
@Bharwcb  i also have the same problem ... any solution ???
