### ISSUE TITLE
print or simple dump method available

### ISSUE THREAD

**Issue by cdaringe** [lorenwest/node-config#274] opened 2015-12-10 17:27 UTC
Hello:

If i `console.log(config)`, I get all my config props + config internals.  I want to visualize only those props which I have defined.  Is there a supporting method to do so?  Perhaps `.toString` or `.toJSON` could proxy it too?  Much appreciated!

E.g., I desire

```js
{
    watchPath: '.test-watch',
    target: {
        basePath: '.test-target',
        fields: [ 'ursi' ]
     },
    logFile: '.penny-collector.log'
}
```

vs

```js
{ watchPath: '.test-watch',
  target:
   { basePath: '.test-target',
     fields: [ 'ursi' ],
     util:
      { watch: [Function],
        setModuleDefaults: [Function],
        makeHidden: [Function],
        makeImmutable: [Function],
        getConfigSources: [Function],
        loadFileConfigs: [Function],
        resolveDeferredConfigs: [Function],
        parseFile: [Function],
        parseString: [Function],
        attachProtoDeep: [Function],
        cloneDeep: [Function],
        setPath: [Function],
        substituteDeep: [Function],
        getCustomEnvVars: [Function],
        equalsDeep: [Function],
        diffDeep: [Function],
        extendDeep: [Function],
        stripYamlComments: [Function],
        stripJSONComments: [Function],
        stripComments: [Function],
        isObject: [Function],
        initParam: [Function],
        getCmdLineArg: [Function],
        getEnv: [Function],
        getRegExpFlags: [Function],
        runStrictnessChecks: [Function],
        util: [Object],
        get: [Function],
        has: [Function],
        _loadFileConfigs: [Function],
        _parseFile: [Function],
        _attachProtoDeep: [Function],
        _cloneDeep: [Function],
        _equalsDeep: [Function],
        _diffDeep: [Function],
        _extendDeep: [Function],
        _stripYamlComments: [Function],
        _stripComments: [Function],
        _isObject: [Function],
        _initParam: [Function],
        _getCmdLineArg: [Function] },
     get: [Function],
     has: [Function],
     watch: [Function],
     setModuleDefaults: [Function],
     makeHidden: [Function],
     makeImmutable: [Function],
     getConfigSources: [Function],
     _loadFileConfigs: [Function],
     _parseFile: [Function],
     _attachProtoDeep: [Function],
     _cloneDeep: [Function],
     _equalsDeep: [Function],
     _diffDeep: [Function],
     _extendDeep: [Function],
     _stripYamlComments: [Function],
     _stripComments: [Function],
     _isObject: [Function],
     _initParam: [Function],
     _getCmdLineArg: [Function] },
  logFile: '.penny-collector.log' }
```

**Comment by markstos** [comment] 2015-12-10 18:15
Closing as a dupe of #223.

**Closed by markstos** 2015-12-10 18:15 UTC
