### ISSUE TITLE
Include my own json config file

### ISSUE THREAD

**Issue by disapointmntPanda** [lorenwest/node-config#631] opened 2020-12-08 12:15 UTC
I would like to inject my `language.json` config files also which will be inside config directory, so that I could use ` const { en } = require('config')`

Currently I am using `default.json` and have defined all the constants there.

Is there a way so that I can use a separate file for it, like `prdocution.json` and `development.json`?

**Comment by lorenwest** [comment] 2020-12-08 13:11
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

---------

Closing this as not a bug or feature request.  Please continue the discussion on [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) if you have further questions.

Node-config is about separating deployment configurations. If you want to also use it for business configurations you can do something like this in  ```defaults.json```
```
...
   "languages": {
     "en-us": require('./languages/en-us.json'),
     "fr": require('./languages/fr.json'),
    },
...
```

**Closed by lorenwest** 2020-12-08 13:11 UTC
