### ISSUE TITLE
ESLint throws some warnings on the types for typescript

### ISSUE THREAD

**Issue by iangregsondev** [lorenwest/node-config#623] opened 2020-11-19 11:40 UTC
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?

ESLint throws errors on the types.

![image](https://user-images.githubusercontent.com/2370364/99661658-71d7db00-2a64-11eb-84bd-9461846aba7e.png)

### Please tell us about your environment:

 -  node-config version: x.x.x
 -  node-version: x.x.x
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by lorenwest** [comment] 2020-11-19 22:14
@iangregsondev what is the expected behavior?  I don't do enough with Typescript to understand how to convert a generic method that returns <any> into a specific one that returns a <string>.  How do other libraries do this?

**Comment by markstos** [comment] 2020-11-20 18:52
We don't maintain the TypeScript definitions. They are in the DefinitelyTyped repo. If you want to propose that the TypeScript types should be hosted here, that can be a separate discussion.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/config

Since the issue isn't with this repo, I'm closing this issue.

**Closed by markstos** 2020-11-20 18:52 UTC
