### ISSUE TITLE
.js files path needs to be qualified by ./  JSON format works great

### ISSUE THREAD

**Issue by asifashraf** [lorenwest/node-config#488] opened 2018-06-06 05:05 UTC
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

If I provide .JS as file extension and verify that the module exists and I can use require() to load it; due to missing "./" the require does not work, however file content reader is able to load that in string. 

When I debugged 
the line 888 in file node_modules/config/lib/config.js
    if (extension === 'js') {
      // Use the built-in parser for .js files
      configObject = require(fullFilename);
    }
above code
gives error saying: "config/default.js" could not be found
however its there. 

The issue is that this needs to be something like
./config/default.js
or "../xxx"

i.e qualifie path

For file content reading in the same file
Line 869node_modules/config/lib/config.js
i,e try {
    fileContent = FileSystem.readFileSync(fullFilename, 'UTF-8');
    fileContent = fileContent.replace(/^\uFEFF/, '');
  }
reads file content properly means it can find the same file with the same path "fullFilename" 
Means fulleFilename variable does not need to be qualified via './' so it works good

### What is the expected behavior?

Both fileContent reader and require module in case of .JS file should be able to read file

### Please tell us about your environment:

 -  node-config version: "config": "^1.30.0",
 -  node-version: v8.9.4
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by asifashraf** [comment] 2018-06-06 05:22
I have made it working by this environment variable
NODE_CONFIG_DIR=./config
But this needs to be exactly as it is. I.e ./ qualified, I guess most of devs using .js format will not find solution easily

**Comment by lorenwest** [comment] 2018-06-06 16:43
This looks pretty serious. If `require('config/default.js')` fails when `reqire('./config/default.js')` works, how could we have gone over 7 years and tens of millions of downloads before finding this out? I use .js files all the time and have never run into this problem - what's different in the environment that @asifashraf is running? What O/S and chip architecture are you running?

**Comment by markstos** [comment] 2018-06-06 20:37
@asifashraf Are you clear how the Node.js `require()` function works? See the docs here:

https://nodejs.org/api/modules.html#modules_all_together

They are quite clear that "f X begins with './' or '/' or '../'", then _it will be loaded as file_, but other wise _it will be loaded as a node module_

Node developers be familiar how files are loaded, which is likely why we haven't received this bug report with 7 years of use and tens of millions of downloads.

**Comment by asifashraf** [comment] 2018-06-07 06:56
@lorenwest 
I am on MacOS Sierra 10.12.6
Node and plugin version mentioned in the first post
I can mention as @markstos mentions that in order to load a module which is written inside code and not in node_modules, we need to qualify the name. This needs to be written in node-config plugin business coding. 

So if I have a module such as
config/default.js

And I will require that in my app.js like

---------app.js----------------
const conf = require('config/default.js')
------------eof app.js --------------

this will not work


however this will work if done like this
---------app.js----------------
const conf = require('./config/default.js')
//notice the "./" qualifier
------------eof app.js --------------

So this is a node's requirement

However this is not the case and requirement for any module inside node_modules
so if i will do require express when express here: node_modules/express then
---------app.js----------------
const express = require('express')
------------eof app.js --------------

this will work without  qualifier and without extension

also this will work

---------app.js----------------
const register = require('typeorm/register')
//When node_modules/typeorm/register is a module  
//no need for qualifier and no need for file extension
------------eof app.js --------------

-------Conclusion-------
We need to change some business code inside the node config plugin with this psudo code

the line 888 in file node_modules/config/lib/config.js
if (extension === 'js') {
// Use the built-in parser for .js files
let qualifier = "./";
configObject = require( qualifier + fullFilename);
}


@markstos Yes I am clear, but this needs to be appended functionality in the plugin node config. They should write it in the plugin, so that if users are loading .js files they must set environment variable; "NODE_CONFIG_DIR=./config" . Without this ENV variable JS files will never work.

**Comment by asifashraf** [comment] 2018-06-07 07:09
@markstos this issue should not be closed, @lorenwest please check 
this was not fixed

**Comment by markstos** [comment] 2018-06-07 13:59
@asifashraf Thanks for clarifying.

@lorenwest I would translate the issue as follows:

  - NODE_CONFIG_DIR should always point to a directory. We can add validation to this value by checking to see if is a format that that Node.js would treat as a directory. If it fails that validation, we could either try to fix that (by assuming it's a relative path and adding a path prefix), or throw an error. 

The issue is complicated by Windows vs POSIX paths, as Windows abosulate paths may look like "C:\\" and use a different path separator.

**Comment by asifashraf** [comment] 2018-06-07 16:54
@markstos yes right. win/unix paths can be identified by algo i.e __dirname will reflect path type

**Comment by iMoses** [comment] 2019-07-17 14:55
@markstos is this issue still relevant?
`locateMatchingFiles` returns `fullFilename` as an absolute path

**Comment by markstos** [comment] 2019-07-17 15:08
I'm not sure this is a bug in `node-config`. Closing for now. If a second user experiences  a related problem, we can re-open.

**Closed by markstos** 2019-07-17 15:08 UTC
