### ISSUE TITLE
Can't find a way to change the default json configuration file path

### ISSUE THREAD

**Issue by joeyzhao0113** [lorenwest/node-config#388] opened 2017-03-07 04:15 UTC
Is there a way to define configuration json files from directory other than `config`? I did't find a way to configure the parameter for below function:

```
util.loadFileConfigs = function(configDir){
...
```

**Comment by markstos** [comment] 2017-03-07 15:00
Besides NODE_CONFIG_DIR? https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir

Closing this, since it's not a bug report or feature request.

**Closed by markstos** 2017-03-07 15:00 UTC
