### ISSUE TITLE
Raw Config

### ISSUE THREAD

**Issue by realtruckjoshdeltener** [lorenwest/node-config#405] opened 2017-04-09 20:12 UTC
Greetings, nice module!  

1 question (I've dug > 1h trying to find the answer) .. Is it possible to just get the basic obj back from the config vs the much larger object with all of the extras?

**Example:**  I have a config with "elastic" :{ "host": localhost, "log": "trace"}, when i do a config.get("elastic") i get an obj with **host** and **log**, but I also get like 20 other things.

makeHidden
util
_attachProtoDeep
_cloneDeep
_diffDeep
...

I literally just want my config, nothing else.  Is that possible?  Currently, I'm having to do things like elasticSearch.Client({host: config.host, log: config.log}) to weed out the extra stuff. (it thinks you are trying to do your own logger if you pass in extra junk)

It sure would be nice just to do elasticSearch.Client(config.get('elastic')) or something similar.

Any advice would be awesome, thanks.

**Comment by zusamann** [comment] 2017-04-09 20:44
can you try destructuring? would probably need babel to use es6 modules though
```es6
import { elastic } from 'config'
console.log(elastic)
```

**Comment by realtruckjoshdeltener** [comment] 2017-04-10 02:50
Ugg, thanks anyway., I'd think a Ferrari of a config class like this would have an easy way, but alas I just used require() to load json.

https://www.bennadel.com/blog/2908-you-can-use-require-to-load-json-javascript-object-notation-files-in-node-js.htm

**Comment by markstos** [comment] 2017-04-10 13:24
Closing as dupe of #223. PR Welcome.

**Closed** 2018-02-02 14:32 UTC
