### ISSUE TITLE
Error: Cannot find module 'config/default.js'. if use .env file to set multiple directories 

### ISSUE THREAD

**Issue by AndyChuang1** [lorenwest/node-config#632] opened 2020-12-11 09:14 UTC
- [ √ ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
My project structure
```
- config
    default.js
- config2
    default.js
app.js
.env
```
config/default.js as below
```
module.exports = {
  app: 'config',
};
```
config2/default.js as below
```
module.exports = {
  msg: 'config2',
};
```
.env files as below
```
NODE_ENV=development
NODE_CONFIG_DIR=./config2:./config
```
My env file use dotenv module in my project.
app.js as below
```
require('dotenv').config();
const config = require('config')
console.log(config)
```
When I run app.js , output throw `Uncaught Error: Cannot parse config file: 'config/default.js': Error: Cannot find module 'config/default.js'`
if I change default.js to default.json, it was working perfectly. I think there are some dir or parse bug over here.
### What is the expected behavior?
I expect output will show as below correctly
```
{
    msg:'config2',
    app:'config'
}
```

### Please tell us about your environment:

 -  node-config version: 3.3.3
 -  node-version: 12.19.0
 
### Other information

I have traced source code find some hints.
I saw this line util.loadFileConfigs form source code as below.
![util.loadFileConfigs](https://i.imgur.com/JPtgxBk.png)
This line only convert first directory to absolute path, so when use `Parser.jsParser = function(filename, content) {
  return require(filename);
}` First directory parse js file pefectly, but second directory. 
So I add as below on util.loadFileConfigs, it can convert multiple directories to make `jsParser` can require proper js file.
```
  const Multifolder = CONFIG_DIR.split(Path.delimiter)
  CONFIG_DIR = Multifolder.reduce((pre,cur)=>{

    if (cur.indexOf('.') === 0) {
      cur = Path.join(process.cwd() , cur);
    }
    if (pre.indexOf('.') === 0) {
      pre = Path.join(process.cwd() , pre);
    }
    return `${pre}:${cur}`
  })
```
I have tested this code manually, it work well.
If there are not any side effects, Can I contribute and fix this bug?
Thank you~

**Comment by markstos** [comment] 2021-10-06 12:01
Closing as dupe of #660

**Closed by markstos** 2021-10-06 12:01 UTC
