### ISSUE TITLE
Silently return null value without error

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [lorenwest/node-config#510] opened 2018-10-13 14:46 UTC
### I'm submitting a ... 
  - [x] feature request

I am currently using this module, what would be really great for me is if instead of having to check if something already exists for potentially empty values, there be a method I can use instead.

So `config.get` would either return null/undefined or a default value.

Thanks

**Comment by lorenwest** [comment] 2018-10-13 15:35
What do you mean by empty values? 

It is important to distinguish between an undefined configuration (one that hasn't ever been set), and a configuration that has a value of null (by default, or overridden).

The ```config.has('name')``` method solves for the first case, and the standard default/overrides solve for the second case. I'd like to understand your use case better in order to consider a new feature or potentially backward incompatible behavior change.

**Comment by piniSolomon** [comment] 2018-12-11 12:14
hi @lorenwest ,
I think what @theboyWhoCriedWoolf  meant was that if you use config.get('someKey') and there is no value defined in the config file it would be good the be able to set a default value and not getting an exception. 
some thing like that:
let value=config.get('someKey', 12);
so if the 'someKey' does not exists in the config file I will get the value 12.

***** if @theboyWhoCriedWoolf  did not meant that I will be happy to have this feature in this awesome library. BTW I use it in every app I made, thank you for that.

**Comment by markstos** [comment] 2018-12-11 19:34
Closing as duplicate of #511.

Please search issues before adding a new one.

**Comment by iMoses** [comment] 2019-07-17 14:57
@markstos you said you'll be closing this but you didn't :)

**Closed** 2019-07-17 15:09 UTC
Labels: duplicate
