### ISSUE TITLE
cli app: config looks in current dir instead of the right spot

### ISSUE THREAD

**Issue by marvinosswald** [lorenwest/node-config#202] opened 2015-03-23 13:32 UTC
If I install my app global I tries to look for an config file in my current directory where I execute the cli app. What do I miss here ? 

Thanks in advance

```
Marvins-MBP:~ marvinosswald$ itan
WARNING: No configurations found in configuration directory:
WARNING: /Users/marvinosswald/config
WARNING: See https://www.npmjs.org/package/config for more information.
/usr/local/lib/node_modules/itan/node_modules/config/lib/config.js:177
    throw new Error('Configuration property "' + property + '" is not defined'
          ^
Error: Configuration property "Store" is not defined
    at Config.get (/usr/local/lib/node_modules/itan/node_modules/config/lib/config.js:177:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/itan/lib/util.js:2:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/itan/cli.js:4:12)
    at Module._compile (module.js:460:26)
```

**Comment by markstos** [comment] 2015-03-23 13:37
In this case, set the NODE_CONFIG_DIR environment variable to point to the directory where the `./config/` directory is:

https://github.com/lorenwest/node-config/wiki/Configuration-Files

This issue is a duplicate of a previously opened issue:
https://github.com/lorenwest/node-config/issues/194

**Closed by markstos** 2015-03-23 13:37 UTC
