### ISSUE TITLE
Arrays are merged by replacement. Why?

### ISSUE THREAD

**Issue by lid3rs** [lorenwest/node-config#562] opened 2019-07-02 20:18 UTC
Documentation reference: [https://github.com/lorenwest/node-config/wiki/Configuration-Files#arrays-are-merged-by-replacement](url)

### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?
According to the documentation "Arrays are merged by replacement", which i do not fully understand why. Fi, i have:
default.json
- "clients": ["a":["one", "two", "three"], "b":["one", "two", "three"]]

developmnent.json
- "clients": ["a":["one"]]

After the config.get("clients") i get an object where two arrays are merged from two files.
 
### What is the expected behaviour?
When i am on development, i expect the object from development to override object from default, not merge with it. 

### Please tell us about your environment:

 -  node-config version: 3.1.0
 -  node-version: v10.15.3

**Comment by lid3rs** [comment] 2019-07-02 20:29
Or am i missing something?

**Comment by lorenwest** [comment] 2019-07-02 21:22
In the above example, the object returned from `config.get('clients')` should look like the object in development.json. Is that not what you're seeing?

**Comment by lid3rs** [comment] 2019-07-03 07:36
I see a merged object from two files like so:

{ 'Client from default.json':
  [ 'a',
  'b' ],
Client from development.json:
  [ 'a' ]
 }

**Comment by lid3rs** [comment] 2019-07-03 07:50
Screenshot: [https://ibb.co/3R9c34J](url)

**Comment by markstos** [comment] 2019-07-03 10:42
In your bug report, "a" is defined as an array. In the screenshots, "a" is defined as an object. Your screenshots show expected behavior for objects.

I'm closing this now because it appears to be a mis-understanding, not a bug. If you believe you've found a bug in `node-config`, please contribute a failing test to the test suite which demonstrates when the module fails when it shouldn't.

**Closed by markstos** 2019-07-03 10:42 UTC

**Comment by lid3rs** [comment] 2019-07-03 11:32
My bad, and i did not know that. Ok, so it means that array of object will be replaced, but objects will be merged, is it correct?

**Comment by lorenwest** [comment] 2019-07-03 12:43
Yes. Objects are merged, arrays are replaced. Arrays are treated like strings because, like strings, you have to use numbers to address inner elements, and numbers don't have semantics.

When you consider what it means to merge "hello" with "world", you start to understand the problems with merging arrays, and why we chose to treat them as a whole vs. their individual parts.
