### ISSUE TITLE
Breaking behavior change in 3.3.0 for env vars defined as empty string.

### ISSUE THREAD

**Issue by rcollette** [lorenwest/node-config#607] opened 2020-05-27 18:26 UTC
### I'm submitting a ... 
  - [X  ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
An environment variable set to an empty value ("") is resulting in an override of a default value

### What is the expected behavior?
An environment variable set to an empty value should not override the default, unless the SemVer version is properly incremented.

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: 12.
 
### Other information

I believe this was due to making the property comparison check for undefined specifically.
https://github.com/lorenwest/node-config/commit/945aed3e47c40e406343f68c3c6aaad8cfe09ea2#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R1036

The use case here is that I have existing environment variables configured on my machine, that I need to clear in a WebStorm runner configuration.   WebStorm cannot unset the variables, only set them so they are set using `SomeVar=`

**Comment by markstos** [comment] 2020-05-27 19:14
Closing as dupe of #593

**Closed by markstos** 2020-05-27 19:14 UTC
Labels: duplicate
