### ISSUE TITLE
The $NODE_CONFIG environment variable is malformed JSON

### ISSUE THREAD

**Issue by victorleungtw** [lorenwest/node-config#394] opened 2017-03-14 08:59 UTC
Following the example in the documation:

$ export NODE_CONFIG='{"Customer":{"dbConfig":{"host":"customerdb.prod"}}}'
$ node myapp.js

I get the following error: The $NODE_CONFIG environment variable is malformed JSON

**Comment by markstos** [comment] 2017-03-14 14:45
I also cannot reproduce the issue locally with node-config. 

Also,  if I copy/paste that string into http://jsonlint.com, it validates fine.

So I'm closing this issue for now. If you can reproduce the issue with a failing test in the test suite, please re-open.

**Closed by markstos** 2017-03-14 14:45 UTC

**Comment by bbakersc** [comment] 2017-12-04 17:43
I am having this issue.  While it *IS* true using the example from the document will work on MacOS running locally, it will not work in Linux environments, and you must pass the NODE_CONFIG variable via the npm command line rather than an `export`.  Passing it via the command line is the only way I have been able to get this to work.  Using v1.28.1 and Docker image mhart/alpine-node:latest ...

**Comment by markstos** [comment] 2017-12-04 20:48
@bbakersc When I said I "could not reproduce the issue", I *was* testing in a Linux environment using the `bash` shell. `bash` should work the same on Linux and macOS. If you've got an example that fails in a Linux environment, please post a reproducible failing test case.

**Comment by amitava82** [comment] 2018-04-09 06:47
I'm getting this error on heroku

**Comment by markstos** [comment] 2018-04-09 14:01
@amitava82 Consider consulting Heroku or their docs about how they are handling environment variables differently than normal.

**Comment by ChetanGoti** [comment] 2019-04-05 11:44
I faced similar issue on Ubuntu 16.04.1 LTS. It worked after I escaped JSON.

Get Malformed JSON error when using: `export NODE_CONFIG={"JSON":{"foo":"bar"}}`
```
ubuntu@chetan:~/temp$ export NODE_CONFIG={"JSON":{"foo":"bar"}}
ubuntu@chetan:~/temp$ echo $NODE_CONFIG
{JSON:{foo:bar}}
```
Works proper: `export NODE_CONFIG={\"JSON\":"{\"foo\": \"bar\"}"}`
```
ubuntu@chetan:~/temp$ export NODE_CONFIG={\"JSON\":"{\"foo\": \"bar\"}"}
ubuntu@chetan:~/temp$ echo $NODE_CONFIG
{"JSON":{"foo": "bar"}}

```
