### ISSUE TITLE
Module config not get loaded if the main app also uses node-config

### ISSUE THREAD

**Issue by skilledDeveloper** [lorenwest/node-config#201] opened 2015-02-25 20:00 UTC
Assume that we have a node module called myModule and we use this module in the main application called myApp. Both myModule and myApp utilizing node-config. When we run myApp, it loads it's config but never loads myModule's config and whenever myModule tries to access its own config, it actually reads myApp's config.
The reason behind this is the way module caching works in node. Very first time it loads myApp config:
``` JavaScript
var myAppConfig = require("config");
```
It then tries to load myModule config. 
``` JavaScript
var myModuleConfig = require("config"); //never loads config as it's already cached
```
Since they both are reuiring the same module, "config", and it is already cached in ```require.cache```, it will not be load myModule's config.

Summary:
If I use node-config in my app and also happen to use  <a href="https://www.npmjs.com/browse/depended/config">a module which depends on node-config </a>, there will be config conflict and either my app or most likely the module's config will not work.

**Comment by markstos** [comment] 2015-02-25 20:39
@skilledDeveloper you are right that caching is involved, but note the wording in the [official docs](http://nodejs.org/api/modules.html#modules_caching):

> "Modules are cached after the first time they are loaded. This means (among other things) that every call to require('foo') will get exactly the same object returned, if it would resolve to the same file."

So if "config" appears in two different file paths in the dependency tree, the dependency should resolve to finding it's "local" version of config, while the parent should resolve to finding config in a parent folder, thus each would get different version. 

I suspect the issue is related-but-different. `node-config` looks for the `config/` folder relative to the *current working directory* not relative to the file that included it (like Node's require does).  So while two different "node-config" modules might be loaded, they could be loading the some configuration. 

If one or both of the modules involved set`NODE_CONFIG_DIR` in the environment before requir'ing `node-config`, it could solve this.  Because of the global nature of setting `process.env.NODE_CONFIG_DIR` the module you depend on may want to do something like this:

```javascript
var origValue = process.env.NODE_CONFIG_DIR;
process.env.NODE_CONFIG_DIR= __dirname +'./config';
var myConfig = require('config');
process.env.NODE_CONFIG_DIR = origValue;
```

That code is untested, and yes the solution is ugly. Other people have requested the ability to resolve the path to configuration as  relative-to-current-file instead of relative-to-current-directory, which would address this case as well.

**Comment by skilledDeveloper** [comment] 2015-02-25 20:52
@markstos What you said about modules would be true only IF we had different config module paths but this never happens in reality as long as they are all the same version. This is because NPM never install the same dependency for the child if it's already installed for the parent.

> the dependency from B to C is satisfied by the fact that A already caused C to be installed at a higher level.

See https://docs.npmjs.com/cli/install

**Comment by markstos** [comment] 2015-02-25 20:56
Ah. Then caching is definitely a real issue here. In the short term, this workaround can be used in one of the modules:

```
delete require.cache[require.resolve('config')];
var config = require('config');
```

That will ensure a fresh copy of `config` is loaded.

**Comment by skilledDeveloper** [comment] 2015-02-25 21:13
This has another issue. If at some point after "force loading" you want to use the original config, you can't. 

I have written a function which loads the proper config based on a namespace. I will share it with you shortly.

**Comment by skilledDeveloper** [comment] 2015-02-25 21:27
``` JavaScript
function getConfig(ns) {
    var config,
        origModule,
        _ = require("lodash");

    if (require.cache[require.resolve("config") + ns]) {
        config = require.cache[require.resolve("config") + ns].exports;
    } else {
        //force load
        delete require.cache[require.resolve("config")];
        config = require("config");

        //rename cache entry
        origModule = _.clone(require.cache[require.resolve("config")]);
        require.cache[require.resolve("config") + ns] = origModule;
        delete require.cache[require.resolve("config")];
    }
   
    return config;
}
```

And we use it like this:

``` JavaScript
//instead of var config = require("config");
var config = getConfig(__filename); 

```

**Comment by lorenwest** [comment] 2015-02-26 15:58
Thanks for the code snippet - this could help someone with the same issue in the future.  

As for node-config, it encourages storing configurations in one place. Sub-modules can declare default configurations using `setModuleDefaults` as described in [sub module configuration](https://github.com/lorenwest/node-config/wiki/Sub-Module-Configuration), and applications using the sub module can override those defaults in their own config directory.

Having survived other systems where configurations are scattered across the filesystem, and where configurations are templates driven by other configurations, this flexibility isn't likely to be added to node-config.

**Comment by skilledDeveloper** [comment] 2015-02-26 18:47
@lorenwest Thanks for the comment. According to <a href="https://github.com/lorenwest/node-config/wiki/Sub-Module-Configuration">Sub Module Configuration</a>:
>Load node-config at the top of your module like normal

I can see two possible scenarios when using node-config in a module:
 1. All module configuration values are set using `setModuleDefaults` and module doesn't have anything defined in the config folder. In this case, like you mentioned, everything works just fine
 2. In addition to default values, module defines and uses some other config values in its own config folder. In this case case, all values defined in the config files under the config folder are lost (never get loaded because of caching issue)

**Comment by lorenwest** [comment] 2015-02-26 21:45
In scenario #2, configurations exist in many places throughout the filesystem. That's the flexibility that node-config doesn't support, and I don't believe it should support.

**Comment by skilledDeveloper** [comment] 2015-02-26 22:52
We are talking about modules which are all using node-config and they are dependent on each other.
IMHO, I don't think it's a flexibility that may or may not be supported. It's a serious issue and can be very dangerous (as it may be silent).

**Comment by lorenwest** [comment] 2015-02-27 03:23
Node-config works well with many co-dependent modules, all using node-config.  By design, there is one place configurations can be stored, so they're usually associated with the application.  They can be in a different directory than the application `process.cwd()`, but they can't be in many directories.

The admittedly serious issue you raise only happens when attempting to store configurations in multiple locations. If configurations are stored in one place, it doesn't matter if many versions of node-config are loaded, because all instances will load the same configurations.

That's also a reason we don't allow mutation of configuration values.  If multiple instances of node-config happen to be loaded (due to node-config being in many places), only one instance would get updated.

Storing configurations in one directory reduces the set of possibilities for misconfiguration, and eliminates the issue raised in this thread.

**Comment by skilledDeveloper** [comment] 2015-02-28 02:53
Yes. As long as all modules configurations are stored in one place, there should be no problems but I doubt it that node-config users are aware of this limitation (feature?).
In addition, merging different modules internal configuration in a single place is against the module independence and increases coupling and we no longer can look at that module as a black-box component.

**Comment by lorenwest** [comment] 2015-03-02 10:08
This shouldn't be a problem, as black box submodules cannot know deployment characteristics of the application containing the submodule.

White box submodules with understanding of their containing application could specify these deployment values, but we have chosen to not support that because of the problems it creates.

If the wiki page on using submodules isn't clear on this, let me know.  I'd be happy to integrate any input you have based on your experiences.

**Comment by vjpr** [comment] 2015-06-13 00:03
Just ran into this problem.

Its very common for a module to have an environment dependent default functionality. E.g. Cache assets if `development`, don't otherwise.

So I want to have:

```
- config
  - default.js
  - development.js
- node_modules
  - module
    - config
      - default.js
      - development.js
```

I think this is nice and elegant.

I expected `node-config` would walk up the tree and merge all configs it finds. Of course, module caching is an issue here.

What do you suggest for my use case?

**Comment by lorenwest** [comment] 2015-06-13 00:48
My personal suggestion is to manage all configurations in one place.  Having configurations stored all over the filesystem is one feature that `node-config` isn't likely to support.

Keeping all app configurations in one place makes it easy to reason about the values of these configurations when it's 3am and your server isn't acting the way it should.

It's one difference between `node-config` and other config management systems.

**Comment by vjpr** [comment] 2015-06-13 02:28
Right now though, I have to hunt through the source files of modules to find out what config options they take (as suggested in the wiki with `setModuleDefaults`). Surely its better to have a config folder in each module instead of that.

I could run one command and view all the configs for all the modules, and see where they are being resolved to. Instead, module developers each choose their own way to represent their config.

**Comment by vjpr** [comment] 2015-06-13 02:32
Maybe some context to what I am working on at the moment...

I want to be able to `npm install something-mongodb` for example, and it automatically wires mongo into my app. For this to work I need default configs. Then the user overrides as neccessary for a central place. Each module I have to shim for this to work, but if more modules used `node-config`, this would be so much easier.

For now, I've just written a custom `config` module which wraps this module and manually reads the configs.

**Comment by lorenwest** [comment] 2015-06-13 14:08
You raise a good point.  Submodule configs set by `setModuleDefaults()` can be anywhere in code, and it would be nice to have a consistent place to find submodule configurations.

If submodules had a config folder, `node-config` would be able to use the `default.{json}` files in that folder to load submodule defaults.  When the sub-module were running as a standalone app (as many do, particularly for tests), that config directory could be used to store configuration overrides.

I've opened a [new feature thread](https://github.com/lorenwest/node-config/issues/225) because this thread is getting long and has other topics. We still have to consider the main topic of this thread when implementing the change.

Thank you for continuing to press on this issue.

**Comment by lorenwest** [comment] 2015-06-13 14:29
While working on related issue #225, we should move towards closure on this issue.  The outstanding issue is the expected behavior when multiple versions of node-config are loaded (usually due to submodule containment).

I'll start out by saying that regardless of how many config versions are loaded, they *should* represent identical configurations.  Options include

    * Assuring copies are identical (hard)
    * Having all copies work on a single global config (messy)
    * Assuring only one version is loaded (not sure this is possible)
    * Others?

**Comment by skilledDeveloper** [comment] 2015-06-13 16:04
I'm happy to see that this thread is active again. 
@lorenwest, Before we could discuss the expected behavior for loading multiple instances of node-config, the caching issue should be fixed first. With current design it's not possible to load multiple configs. 

Currently something like your option 3 (if I understood correctly) is happening but we never know which one is loaded.

**Comment by lorenwest** [comment] 2015-06-13 16:54
The module cache has nothing to do with where node-config loads configurations.  Regardless of the module that calls `require('config')`, it will always load configs from the same place (the /config directory under the process current working directory - unless overridden).  

My understanding was that you wanted submodules to have a different place for their configurations from the main app, and issue #225 addresses that feature.

The way NodeJS finds modules could result in multiple instances of node-config being loaded into the cache (also discussed in this thread).  Multiple versions of config in memory has a different set of problems, which I would like this thread to discuss.

Is there a different issue that you are having?

**Comment by skilledDeveloper** [comment] 2015-06-13 17:22
I think we are not on the same page. 

> The way NodeJS finds modules could result in multiple instances of node-config being loaded into the cache

This is not true. Only one version (first call) is loaded an chached. (See my comment above regarding npm)

**Comment by lorenwest** [comment] 2015-06-14 04:10
@skilledDeveloper, multiple instances of `node-config` are loaded into `schema.cache` when submodules have copies of `node-config` in their own `node_modules` subfolders.  This happens often, usually without anyone noticing, because all instances load configs from the same place.

The issue leading to the creation of this thread should be resolved with #225.  If there is only one instance of `node-config` in the `require.cache` (as is in your case), each submodule will have the opportunity to load their defaults from their own `/config` directory into this single instance.

The remaining issue is when multiple instances of `node-config` are in the `require.cache`, and only one instance is updated with submodule defaults.

I would like to explore options for resolving this remaining issue:

    * Assuring copies are identical (hard)
    * Having all copies work on a single global config (messy)
    * Assuring only one instance is loaded (not sure this is possible)
    * Others?

**Comment by skilledDeveloper** [comment] 2015-06-14 04:45
>  when submodules have copies of `node-config` in their own `node_modules` subfolders

If the main application (ie. parent) uses `node-config`, `npm` does NOT install it again in the sub-module (child) `node-config` folder. 
In other words, if you have an application which uses  `node-config` and 10 other sub-modules that use  `node-config` too, `npm install` will result in creating one `node_modules/node-config` folder.

This is explained here: https://docs.npmjs.com/cli/install#algorithm

**Comment by lorenwest** [comment] 2015-06-14 05:47
You're confusing NPM with NodeJS.  NPM generally does a good job of not duplicating installs under sub node_modules directories.

That doesn't mean duplicates don't exist.  When one module defines it's dependency on config@1.8.0, and another defines their dependency on config@1.12.0, NPM follows instructions and installs two different versions of node-config.  At runtime, NodeJS simply loads the "closest" package available.  If only one exists, then there will be only one version in cache.  In the above example, NodeJS finds and makes available config@1.8.0 for the first module, and config@1.12.0 for the second.

This is an extremely powerful feature of NodeJS compared with other languages, but it has a side effect of 2 instances in the require.cache.

If you use many external libraries, this is almost certainly happening with your app.  If you list all modules under all node_module directories (and sub directories) under your app, I would be surprised if there weren't duplicates.  Node caches these as separate module instances.

**Comment by skilledDeveloper** [comment] 2015-06-14 06:00
What if they are all using the **same version** of node-config (which is more likely)?

**Comment by lorenwest** [comment] 2015-06-14 06:07
> What if they are all using the same version of node-config (which is more likely)?

Then

> The issue leading to the creation of this thread should be resolved with #225.

I'm creating a different issue for the multiple instance issue.  Apologies for stepping all over your thread, since this isn't an issue for you.

**Comment by skilledDeveloper** [comment] 2015-06-14 06:35
Cool. Thanks

**Comment by Bruce17** [comment] 2015-06-25 15:04
Well I'm having the same issue here.
I solved it using this code:

```js
process.env.NODE_CONFIG_DIR = __dirname + '/config/';
var config = require('config');
```

**Comment by Bruce17** [comment] 2015-07-10 09:01
I forked your module and implemented a working fix to this issue (I needed a solution asap).

Have a look at it: https://github.com/Bruce17/node-config/commit/9a6b19c5df601580dd2aafa354c45b7723626d1e

**Comment by lorenwest** [comment] 2015-07-10 15:44
This thread has many issues, and I'm not sure which one you're having which led to this solution.  The proposed solution for submodules having their own /config directory is in #225, and discussions about alternatives should be made in that thread.  If your issue is multiple node instances, then #226 is the place to have that discussion.

**Closed** 2015-07-10 15:44 UTC

**Comment by alexindigo** [comment] 2016-02-23 03:29
@skilledDeveloper @Bruce17 I created a module that addresses this concern while mimicking `node-config` functionality. So if it's something you're still interested in, you can check it out: http://npmjs.org/configly
