### ISSUE TITLE
Use config.get('SOMETHING') for retrieve env variable

### ISSUE THREAD

**Issue by baloran** [lorenwest/node-config#395] opened 2017-03-14 09:55 UTC
I have a problematic I want to use config.get for retrieve env variable if exist nor use the config file. 

It's not possible ?

**Comment by baloran** [comment] 2017-03-14 10:19
I have made a PR #396

**Comment by markstos** [comment] 2017-03-14 14:48
Closing as a duplicate of #381. Please read that issue and related linked tickets for the rationale.

**Closed by markstos** 2017-03-14 14:48 UTC
