### ISSUE TITLE
Files loaded using NODE_APP_INSTANCE must have matching extensions

### ISSUE THREAD

**Issue by loudwinston** [lorenwest/node-config#512] opened 2018-10-17 20:52 UTC
### I'm submitting a ... 
  - [ X ] bug report

### What is the current behavior?
Using `NODE_APP_INSTANCE` seems to only allow files with the same extension as the equivalent stage config file.  For example, if you have `development.json` and `development-{NODE_APP_INSTANCE}.js`, `config` will not load the values from `development-{NODE_APP_INSTANCE}.js`.  

Reproduction steps:
1. Create a `development.json` file, with some values.  
1. Create a `development-foo.js` file, and export an object that overrides the values defined in `development.json`
1.  `require('config')` in application, setting `NODE_APP_INSTANCE=foo` as environment variable

Actual Behavior: 
Value in `config` will be what was defined in `development.json`

### What is the expected behavior?
Value in `config` should be what was defined in `development-foo.js`

### Please tell us about your environment:

 -  node-config version: 2.0.1
 -  node-version: 8.11.2

**Comment by markstos** [comment] 2018-10-18 14:30
@loudwinston Would be helpful would be checking out this project from Git and adding a test to the test suite which reproduces the issue.

**Comment by markstos** [comment] 2018-10-18 14:31
@loudwinston Also check out the related code:
https://github.com/lorenwest/node-config/blob/master/lib/config.js#L589

I think you'll see there is no "matching extension" logic

**Comment by loudwinston** [comment] 2018-10-18 14:57
@markstos I will try to do that.  

However, looking at the logic thats in https://github.com/lorenwest/node-config/blob/master/lib/config.js, I can guess at the cause of this bug.  

Configs are joined by first iterating through available file extensions.   For each possible file extension, the code checks for the presence of `${NODE_ENV}.{EXT}` and `${NODE_ENV}-{NODE_APP_INSTANCE}.{EXT}`.    Since `.json` is listed **after** `.js` in the list of extensions, `.json` files will always take precedence over `.js` files when created the combined configuration.  

Give my example above, the order that the configs would be loaded is

1. `development.js` (doesn't exist)
1. `development-foo.js` (exists)
1. `development.json` (exists) (**overwrite happens here**)
1. `development-foo.json` (doesn't exist)

This would cause anything in `develpment.json` to override whatever is in `development-foo.js`, which is the errant behavior that I am seeing.

**I can confirm that this is what's happening in the example that I provided above.**  Using the example setup in the original ticket description, I put some debugging statements into `config.js` and the output was the following

```
Loading /Users/loudwinston/config-bug-test/config/default.json
Loading /Users/loudwinston/config-bug-test/config/development-foo.js
Loading /Users/loudwinston/config-bug-test/config/development.json
```

**Comment by markstos** [comment] 2018-10-18 15:05
@loudwinston I would agree the code looks like it might not match our documentation on file load order: https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order  Could you express your confirmation as a new test in our test suite, and then possible contribute a bug fix as well?

**Comment by loudwinston** [comment] 2018-10-18 15:08
@markstos Unfortunately I doubt that I will have time to do this anytime soon.   If that situation changes, I will certainly update this ticket with a PR.

**Comment by markstos** [comment] 2018-10-18 15:16
@loudwinston It's OK, we might not have time, either.

**Comment by loudwinston** [comment] 2018-10-18 15:21
@markstos I'm working with my corporate legal and compliance team to get permission to contribute a fix for this bug.  

In the meantime, perhaps an alternately would be to consider updating the documentation on file load order to mention this issue?

**Comment by markstos** [comment] 2018-10-18 19:21
@loudwinston You are the first person in about 5 years or so to notice this, while there are millions of downloads. I expect most people keep all their config files in the same format. To trigger this issue, you have 1. Mix file formats. 2. Use particular types and combinations of config files. 3.  Mix your file formats in the right order to trigger it. Mixing them in the reverse order won't trigger it.  I think time of the issue is better spent resolving it. The presence of this issue servers as a form of documentation that it exists.

**Comment by loudwinston** [comment] 2018-10-18 19:47
@markstos That is, of course, your decision to make as a maintainer of the repo.

**Comment by joshghent** [comment] 2018-12-04 11:44
@markstos @loudwinston After reading through this issue, is this an issue that you actually want fixing? I believe the fix would be to order all `xxx-{instance}.EXT` after everything else? If so I can work on this.

**Comment by markstos** [comment] 2018-12-04 15:55
@joshghent A patch is welcome to make the file load order work as it is documented to work. Our spec on file load order is here: https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order

This issue asserts there is a problem in some cases when file extensions are mixed:
https://github.com/lorenwest/node-config/issues/512#issuecomment-431042222

**Comment by loudwinston** [comment] 2018-12-04 16:07
@joshghent After reviewing the code a bit more, I think the root problem is that the `-{INSTANCE}` named files are treated with a special case [here](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L607), rather than being included in the overall `baseNames` array that it is created above this.

Perhaps the problem would be solved if the code was modified to add the `-{INSTANCE}` files (minus extensions) to this array in the same way that other files are added?  Respecting the documented file load order, of course.

You would still have the issue of conflicts if you have 2 files with the exact same `baseName` but different extensions, but this is an existing issue unrelated to `-{INSTANCE}` handling specifically.  As @markstos said in an earlier comment, this is probably an exceedingly rare occurrence.  Perhaps as part of the changes being discussed, the code could also be modified to log a warning in this case?

**Comment by markstos** [comment] 2018-12-04 19:42
@loudwinston It seems fine to warn if you have both `development-foo.js` and `development-foo.json`, or other cases where the only difference is a file extension.

That seems most likely to be an accident. It seems confusing and rarely desirable. Also, there's no clear order to try resolve that conflict in. "Alphabetical" seems arbitrary. 

As long as the documented load order is preserved, your solution seems fine.

**Comment by loudwinston** [comment] 2018-12-04 19:53
@markstos 

>> That seems most likely to be an accident.

That's why I thought it'd be good to have a warning in that case. Mixing file extensions for different files (e.g. `default.json`, `development.js`, `local.yaml`) might have a limited use case, but I can't think of a scenario where someone would **want** to have duplicate files with different extensions  

FWIW I'm still working on getting approval to contribute to this library - the process is moving a bit more slowly than I'd like.  @joshghent I'd be happy to discuss potential solution further and review any code that you contribute if that would be helpful in the meantime.

**Closed** 2019-07-03 14:17 UTC
Labels: 3.0, pr-welcome
